# Generated by Django 3.1 on 2020-08-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200819_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
